### ISSUE TITLE
Doesn't work with ruff 0.0.265

### ISSUE THREAD

**Issue by CervEdin** [Nealium/ruff-quickfix#4]
Nice! I couldn't get it to work with 0.0.265 and didn't get any error, just no output.
Which version of `ruff` does this target?

```python
    cmd = f"ruff check {path} --output-format concise"
```

Also, I would suggest taking a look at `--output-format json`

**Comment by Nealium** [comment]
It now works with `ruff==0.0.265`. I'm not sure where the cut off is, I've always found that hard to find

but JSON was a good call! Now there's an actual catch for all errors/warning and there won't be just empty outputs.

**Comment by CervEdin** [comment]
Nice! FWIW, I was just using an old version of ruff and not getting an error was the part which was causing the unexpected behavior and I wouldn't expect this to work on any old version.
